function params = system_parameters()
    params.m = 2000; %kg
    params.rho = 1.225; %kg /m3
    params.C_d = 0.4; %
    params.Af = 1.6; %frontal area of vehicle 
    params.V_wind = 10 ;  %m/s
    params.a = 1.1;         %front_axel - CG
    params.b = 1.2;         % rear axel - CG
    params.l =  1.1 + 1.2;  %%m length of wheel base
    params.tf =  1.58; % track idth of wheel base 
    params.tr = 1.58; % track width of rear wheel base
    params.w = 1.58; % vehicle width
    params.Izz_v = 2000 * ((1.1+1.2)^2 + (1.58)^2) / 12;  %vehicle intertia 
    params.max_torque = 450; %Nm
    params.max_power =  225* 10^3;
    params.C_x = 50000 ;     %N
    params.C_y = 40000 ;  %N/Radlateral coefficient of stiffness
    params.R_f = 0.334; % m 
    params.R_r = 0.334; % m
    params.tire_m_f = 12; %mass in Kg
    params.tire_m_r = 12; %mass in Kg
    params.Iyy_w_f = 0.5 * 12 * 0.334; 
    params.Iyy_w_r = 0.5 * 12 * 0.334;
    % params.slip_max = (params.max_torque * accel / (params.R_f *2 * params.C_x));
    params.slip_min = -0.1;
    params.no_drive_wheels = 2;
    params.g = 9.8; %m/s2
    params.h = 0.25; %m
end
